'use strict'
// CPU fixture executes the native workflow. The Map models Host evidence writes;
// these are not GPU measurements and no optimization source is authored here.
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');const run=require('../lib/run-workflow.js');const source=fs.readFileSync(path.resolve(__dirname,'../../../AccelOpt/accelopt-kernel-optimization.js'),'utf8');
const args={kernel_path:'/fixture/seed.cu',exp_dir:'/fixture/exp',backend:'cuda',iterations:2,breadth:1,samples_per_plan:2,integration_pattern:'sol_execbench_solution',sol_cli:'/fixture/sol',sol_task_dir:'/fixture/task',sol_substrate_dir:'/fixture/substrate',sol_seed_dir:'/fixture/seed',sol_definition_path:'/fixture/definition.json'};
const hash=s=>crypto.createHash('sha256').update(s).digest('hex');
const full=lat=>({compiled:true,correct:true,measurement_valid:true,full_workload_set:true,output_contract_valid:true,n_pass:17,n_total:17,candidate_latency_aggregate_ms:lat,latency_ms:lat,speedup:1.5,speedup_vs_seed:.020/lat});
async function replay(){const writes=new Map(),requests=[],agents={'read-baseline':{kernel_code:'SEED',op_type:'gemm',key_functions:['run']},'ncu-baseline':{latency_ms:.012,ncu_available:true}},evals={'sol-seed-baseline':{...full(.020),candidate_role:'baseline'}};
 const host=req=>{const idx=requests.length;requests.push(req);const binding={verified:true,binding_path:req.bindingOut,candidate_id:req.candidateId,candidate_sha256:hash(req.candidateSource)};for(const field of ['candidatePath','solutionOut','benchOut','bindingOut','normalizedOut'])writes.set(req[field],{source:req.candidateSource,binding});return {...full([.016,.018,.019,.0195][idx]),artifact_binding:binding};};
 for(let i=0;i<2;i++){agents[`plan-${i}-0`]={title:'p',plan:'fixture',ncu_evidence:'fixture',expected_impact:'fixture'};for(let j=0;j<2;j++){agents[`impl-${i}-p-v${j}`]={code:`SOURCE_${i}_${j}`};for(const id of [`plan_0_sample_${j}`,`iter_${i}_plan_0_sample_${j}`]){agents[`eval-${id}`]={is_compilable:true,is_correct:true,estimated_speedup:99,estimated_latency_ms:.001};evals[`sol-eval-${id}`]=host;}}}
 const {result}=await run(source,args,agents,evals);return {result,requests,writes};}
test('all Host candidate IDs and evidence paths are unique across two native rounds',async()=>{const {requests}=await replay();assert.equal(requests.length,4);for(const key of ['candidateId','candidatePath','solutionOut','benchOut','bindingOut','normalizedOut'])assert.equal(new Set(requests.map(r=>r[key])).size,4,key+' reused');for(let i=0;i<4;i++)assert.match(requests[i].candidateId,new RegExp(`^iter_${Math.floor(i/2)}_`));});
test('slower second round cannot overwrite first best source or binding',async()=>{const {result,requests,writes}=await replay();assert.equal(result.best_kernel_code,'SOURCE_0_0');assert.equal(result.best_candidate_binding.binding_path,requests[0].bindingOut);const saved=writes.get(result.best_candidate_binding.binding_path);assert.equal(saved.source,result.best_kernel_code);assert.equal(saved.binding.candidate_sha256,hash(result.best_kernel_code));assert.equal(writes.get(requests[0].candidatePath).source,result.best_kernel_code);assert.equal(result.overall_speedup,1.25);});
