'use strict'
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');const run=require('../lib/run-workflow.js');const source=fs.readFileSync(path.resolve(__dirname,'../../../CUDALLM/cudallm-fsr-kernel-generation.js'),'utf8');
const base={problem_definition:'fixture gemm',reference_code_path:'/fixture/seed.cu',exp_dir:'/fixture/exp',integration_pattern:'sol_execbench_solution',sol_cli:'/fixture/sol',sol_task_dir:'/fixture/task',sol_substrate_dir:'/fixture/substrate',sol_seed_dir:'/fixture/seed'};
const valid={compiled:true,correct:true,full_workload_set:true,output_contract_valid:true,measurement_valid:true,n_pass:17,n_total:17,candidate_latency_aggregate_ms:.018,latency_ms:.018,speedup:1.5,speedup_vs_seed:.020/.018,artifact_binding:{verified:true,binding_path:'/fixture/binding.json'}};
async function replay(host,reply={compiled:true,correct:true,speedup:123,latency_ms:.001},native=false){let measured=0;const agents={},evals={'sol-seed-baseline':{...valid,candidate_role:'baseline',candidate_latency_aggregate_ms:.020}};for(let i=0;i<(native?8:1);i++)for(let j=0;j<(native?2:1);j++){agents[`generate-kernel-${i}-${j}`]={candidate_code:`SOURCE_${i}_${j}`};agents[`evaluate-${i}-${j}`]=reply;evals[`sol-eval-${i}-${j}`]=request=>{measured++;return host};}const result=await run(source,native?base:{...base,iterations:1,samples_per_feature_set:1},agents,evals);return {...result,measured};}
for(const [name,h] of [['contradictory',{...valid,correct:false,full_workload_set:false,measurement_valid:false,n_pass:16,speedup:0}],['missing',null],['partial',{...valid,full_workload_set:false,n_pass:16}],['measurement missing',{...valid,measurement_valid:undefined}],['unbound',{...valid,artifact_binding:null}],['nonnumeric',{...valid,speedup_vs_seed:'123'}]])test(`${name} Host feedback cannot be overridden`,async()=>{const {result}=await replay(h);assert.equal(result.best_kernel_code,'');assert.equal(result.best_speedup,0);assert.equal(result.candidates[0].eval.correct,false);});
test('agent rejection cannot overwrite fully valid Host measurement',async()=>{const {result}=await replay(valid,{compiled:false,correct:false,speedup:0,latency_ms:999});assert.equal(result.best_kernel_code,'SOURCE_0_0');assert.equal(result.best_speedup,.020/.018);assert.equal(result.best_latency_ms,.018);assert.equal(result.best_candidate_binding.binding_path,'/fixture/binding.json');assert.equal(result.generated_kernel_path,'/fixture/exp/cudallm_iter_0_sample_0.cu');});
test('inflated fabricated agent values are replaced by bound measurements',async()=>{const {result}=await replay(valid);assert.equal(result.best_speedup,.020/.018);assert.equal(result.candidates[0].eval.passed_tests,17);assert.equal(result.candidates[0].eval.total_tests,17);assert.equal(result.candidates[0].eval.compiled,true);});
test('normal full native eight rounds and two samples retain Host authority',async()=>{const {result,measured}=await replay(valid,undefined,true);assert.equal(measured,16);assert.equal(result.iterations,8);assert.equal(result.samples_per_feature_set,2);assert.equal(result.candidates.length,16);assert.equal(result.best_speedup,.020/.018);assert.equal(result.best_kernel_code,'SOURCE_0_0');});
